---
    - name: Install Java
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Add Jenkins APT key
      apt_key:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        state: present

    - name: Add Jenkins APT repository
      apt_repository:
        repo: deb https://pkg.jenkins.io/debian-stable binary/
        state: present

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present
      ignore_errors: True
      register: jenkins_install_result

    - name: Start Jenkins service
      service:
        name: jenkins
        state: started
        enabled: yes
      when: jenkins_install_result is failed

    - name: Ignore Jenkins installation failure
      debug:
        msg: "Jenkins installation failed, but continuing with the playbook."
      when: jenkins_install_result is failed

    # - name: Fetch initialAdminPassword file
    #   fetch:
    #     src: "/var/lib/jenkins/secrets/initialAdminPassword"
    #     dest: "./"
    #     flat: yes

    - name: Include Jenkins credentials
      include_vars: jenkins_credentials.yml

    - name: Set GIT_TOKEN variable
      set_fact:
        GIT_TOKEN: "{{ git_token }}"

    - name: Set Git global credentials helper
      shell: git config --global credential.helper "store --file=~/.git-credentials"
      environment:
        MY_GIT_TOKEN: "{{ GIT_TOKEN }}"
      register: git_config_result
      changed_when: false

    - name: Store Git credentials
      copy:
        content: "https://{{ git_username }}:${GIT_TOKEN}@github.com"
        dest: ~/.git-credentials
        mode: "0600"
      when: git_config_result.rc == 0

    - name: Publish Jenkins pipeline job
      jenkins_job:
        name: SamplePipeline
        config: "{{ lookup('file', '/home/altron/GCPProject/pipeline_config.xml') }}"
        url: http://localhost:8080  
        user: "{{ jenkins_user }}"
        password: "{{ jenkins_api_token }}" 
        state: present
