# # # ---
#   - name: Download Long Term Jenkins release
#     get_url:
#       url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
#       dest: /etc/yum.repos.d/jenkins.repo

#   - name: Import jenkins key from url
#     ansible.builtin.rpm_key:
#       state: present
#       key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

#   # - name: yum update
#   #   yum:
#   #     name: '*'
#   #     state: latest

#   - name: Install wget
#     yum:
#       name: wget
#       state: present

#   - name: Install java
#     yum:
#       name: java-11-openjdk
#       state: present

#   - name: Install jenkins
#     yum:
#       name: jenkins
#       state: latest

#   - name: daemon-reload to pick up config changes
#     ansible.builtin.systemd:
#       daemon_reload: yes

#   - name: Start jenkins
#     ansible.builtin.systemd:
#       name: jenkins
#       state: started


#   - name: Install java
#     yum:
#       name: java-11-openjdk
#       state: present

---
    - name: Install Java
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Add Jenkins APT key
      apt_key:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        state: present

    - name: Add Jenkins APT repository
      apt_repository:
        repo: deb https://pkg.jenkins.io/debian-stable binary/
        state: present

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present
      ignore_errors: True
      register: jenkins_install_result

    - name: Start Jenkins service
      service:
        name: jenkins
        state: started
        enabled: yes
      when: jenkins_install_result is failed

    - name: Ignore Jenkins installation failure
      debug:
        msg: "Jenkins installation failed, but continuing with the playbook."
      when: jenkins_install_result is failed

    # - name: Fetch initialAdminPassword file
    #   fetch:
    #     src: "/var/lib/jenkins/secrets/initialAdminPassword"
    #     dest: "./"
    #     flat: yes