---

- name: Installing Mysql and dependencies
  package:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - default-mysql-server
    # - mysql-client
    - python3-mysqldb

- name: start and enable mysql service
  service:
    name: mysql
    state: started
    enabled: yes

- name: Include MySQL user credentials
  include_vars: mysql_user_credentials.yml

- name: creating mysql user
  mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    priv: '*.*:ALL'
    host: '%'
    state: present
  register: mysql_user_result

- name: Print MySQL user creation result
  debug:
    var: mysql_user_result

- name: creating db
  mysql_db:
    name: "root"
    state: present
  register: mysql_db_result

- name: Print MySQL db creation result
  debug:
    var: mysql_db_result

- name: MySQL tablosu oluştur
  mysql_query:
    login_db: root
    query: "CREATE TABLE my_table (id INT AUTO_INCREMENT PRIMARY KEY,title VARCHAR(255),description TEXT,due_date DATETIME);"

- name: Insert rows into MySQL table
  mysql_query:
    login_db: root
    query: "INSERT INTO my_table (title, description, due_date) VALUES ('Buy milk', 'Buy milk at the grocery store', NOW()), ('Clean the house', 'Clean the house on Saturday', '2023-07-25 19:45:23');"

- name: Restart MySQL service
  service:
    name: mysql
    state: restarted


- name: Enable remote login to mysql
  lineinfile:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    regexp: '^bind-address'
    line: 'bind-address = 0.0.0.0'
    backup: yes


- name: Restart mysql
  service:
    name: mysql
    state: restarted