---

- name: Install PHP and Nginx
  apt:
    name: 
      - php
      - php-fpm
      - php-mysql
      - nginx
    state: present


- name: Start and enable PHP-FPM service
  service:
    name: php7.4-fpm 
    state: started
    enabled: true


- name: Start and enable Nginx service
  service:
    name: nginx
    state: started
    enabled: true


- name: Copy Green HTML File
  copy:
      src: /home/altron/GCPProject/index/green.php
      dest: /var/www/html/index.nginx-debian.html
