---
- name: Install Jenkins
  hosts: all
  remote_user: ansible
  become: yes
  vars:
    jenkins_home: /var/lib/jenkins
    jenkins_port: 8080
    jenkins_user: jenkins
    jenkins_group: jenkins


  roles:
  - jenkins
